
[avaProbs_general]

rerun_find_WL =1 
rerun_assign_avaprobs = 1
# initilization_type = station
initilization_type = profile

#SNOW_PROFILES_FOLDER=../lawis-profiles
SNP_INPUT_FOLDER= ../input/ISEE_PROF/
output_path = ../output/

# SLOPE_ASPECTS=  flat N E S  W 
SLOPE_ASPECTS=flat

season_start =2021-10-23
season_end = 2022-05-28
drytime= 6
wettime=15
#option 'snp' 'cro' not implemented
scmopt = snp 
# reales 'trigger' or 'natural'
release = trigger 

# thresholds to find/assign WL 
[avaProbs_thresholds_aps] 
alp=38
calcFEM=0          
owSCtaup=0                 
lookat= 0                    
aggrgtDAPs= 1 
aggrgtdiff=0.03 
outputDAP=0      
#%% basic decision data   ## matlab line 84
dropini=5
droppro=.64            
drftthrsh=.4           
minSLdens=120         
minnsthrsh=.05       
nsthrsh=.2            
minSLthrsh=.2         
lwcthrsh=0.008 

lwcthrsh_0 =0.01 
lwcthrsh_1 =0.03 
release = release       
# minfracswetsnow=0.7  

# thresholds for assigning a avaprob to WL
[avaProbs_thresholds_avaprob_snp] 
damthrshnap=99      
inithrshnap=999    
propthrshnap= 99     
damthrshpap=18      
# inithrshdap= 2x inithrshpap; propthrshdap= 2x propthrshpap;
inithrshpap= 1.31       
propthrshpap=.42    
drftthrsh=3         
dysisomax=3
lwcthrsh=0.01

lwcthrsh_0 = 0.01 
lwcthrsh_1 = 0.03 

[avaProbs_thresholds_avaprob_cro]
damthrshnap=27     
propthrshnap=.55    
damthrshpap=27     
# inithrshdap= 2x inithrshpap; propthrshdap= 2x propthrshpap;
#% inithrshpap=1;        %snp:1;
propthrshpap=.56   
drftthrsh=265      
dysisomax=3
lwcthrsh=0.008
lwcthrsh_0 = 0.01 
lwcthrsh_1 = 0.03 

[INFO]
#avaProbs_thresholds_aps 
; alp=38
; calcFEM=0           #%=1; means use FEM model to calcuate shear stress at WL, slab modulus, slab tensile stresses
; owSCtaup=0                  #%=1; means overwrite snow cover shear strength (tau_p)
; lookat= 0                       #%say if you want to see a graph
; aggrgtDAPs= 1 
; aggrgtdiff=0.03 #%aggregate DAPs if they are located within aggrgtdiff [m]
; outputDAP=0                   #% index of DAP to output; can create table: table(DAPLAYEROUT_txt,DAPLAYEROUT_dou)
; #%% basic decision data   ## matlab line 84
; dropini=5
; droppro=.64            #thresholds of initiation and propgation criteria for dropping (deep-)persitent weak layers
; drftthrsh=.4           #min height of snow drifts [m], snp=:0.4m, cro:.2
; minSLdens=120         #120,min average density of a potential slab
; minnsthrsh=.05        #def.: 0.05m,min. amount of new snow [m], to start identifying problems (we find WL with windows, do don't care about +-5cm of fresh snow)
; nsthrsh=.2            #def.: .2,amount of new snow [m] (within 48 or 24 hr), to keep a non-persis. problem for one more day
; minSLthrsh=.2         #def.: .2,min. slab thickness [m] to be considered a healthy slab, 
; lwcthrsh=0.008 
; release = release       #.008[snp], Christophs LWC threshold for maztrix flow: 0.03; threshold for preferential flow: 0.01
; # minfracswetsnow=0.7   #min fraction of snow height for wap, def.: 0.7 * max snow height during season

; [avaProbs_thresholds_avaprob_snp] # thresholds for assigning a avaprob to WL
; damthrshnap=99      # snp 8hours
; inithrshnap=999     # do not constrain
; propthrshnap= 99     # snp: .32m
; damthrshpap=18      # snp:18 8 18 hours
; # inithrshdap= 2x inithrshpap; propthrshdap= 2x propthrshpap;
; inithrshpap= 1       # snp:1;
; propthrshpap=.4     # snp:.24 .318 .4;
; drftthrsh=3         # snp.5[m]; min height of snow drifts
; dysisomax=2
; lwcthrsh=0.008
; release =release

; [avaProbs_thresholds_avaprob_cro]
; damthrshnap=27      # cro 15hours
; propthrshnap=.55    # cro: .36m
; damthrshpap=27      # crp: 15 27 hours
; # inithrshdap= 2x inithrshpap; propthrshdap= 2x propthrshpap;
; #% inithrshpap=1;        %snp:1;
; propthrshpap=.56   # cro:.36 .43;
; drftthrsh=265      # cro.265[?]; min height of snow drifts
; dysisomax=3
; lwcthrsh=0.008
