################################################################################
# Copyright 2022 Avalanche Warning Service Tyrol                               #
################################################################################
# This is free software you can redistribute/modify under the terms of the     #
# GNU Lesser General Public License 3 or later: http://www.gnu.org/licenses    #
################################################################################

[SNOWPRO]
PLOT_SNP_EVO=TRUE
PLOT_PROFILE=FALSE
PLOT_SNP_EVO_AND_PROFILE=FALSE
PRO_FILE_PATH=./data/Ottenspitze.pro
OUTPUT_DIR=./output
COLOR_SCHEME=IACS2
OUTPUT_NAME=NONE
HEIGHT_MAX=NONE

[SNOWPRO-EVO]
RESOLUTION=1h
VAR=Punstable
SECOND_VAR=NONE
START_DATE=NONE
END_DATE=NONE

[SNOWPRO-PROF]
# DATETIME=2022-02-03T12h00
# DATETIME=2022-02-01T10h00
DATETIME=2022-03-10T10h00

[CONFIG-INFO]
# HEIGHT_MAX in cm
# COLOR_SCHEME = 'SARP', 'SARPGR', 'IACS2'
# RES = 1h, 2h, 3h, 1d 
# SECOND_VAR=NONE,Sk38,Sn38,LWC
# START_DATE=2021-10-01
# END_DATE=2022-06-01