[SNOWPRO]
PLOT_SNP_EVO=TRUE
PLOT_PROFILE=FALSE
PLOT_SNP_EVO_AND_PROFILE=FALSE
# PRO_FILE=data/LWDTIROL_SNP-FC-AXLIZ.pro
# PRO_FILE=data/campass_res.pro
PRO_FILE=data/AXLIZ1.pro
# PRO_FILE=/Users/tennismichel/LWD/HEF-21-22/snp_output/TEUFELSEGG_HEF-DENSITY.pro
COLOR_SCHEME=SARPGR

[SNOWPRO-EVO]
RESOLUTION=2h
# RESOLUTION=avaProb
VAR=grain_type
# VAR=density
SECOND_VAR=RTA
# START_DATE=NONE
# END_DATE=NONE
START_DATE=2021-10-01
END_DATE=2022-06-01


[SNOWPRO-PROF]
# DATETIME=2022-02-03T12h00
DATETIME=2022-02-01T10h00

[INFO]
# COLOR_SCHEME = 'SARP', 'SARPGR', 'IACS2'
# RES = 1h, 2h, 3h, 1d 
# SECOND_VAR=NONE,Sk38,Sn38,LWC