[AVAPRO]
SNP_DIR         = ./output/snp
SNP_FILE        = snowprofile00000.pro
OUTPUT_DIR      = ./output/avapro
OUTPUT_DIR_FIGS = ./output/avapro-figures

rerun_find_WL          = 1
rerun_assign_avaprobs  = 1
run_visualize_avaprobs = 1

DATE_OPERA          = TODAY
initilization_type  = profile
drytime             = 6
wettime             = 15
res                 = 1d
debug               = 0
scmopt              = snp

# Only for type station
season_start        = 2023-01-01
season_end          = 2024-01-01

[AVAPRO-THOLDS-WL]
calcFEM=0          
owSCtaup=0                 
lookat= 0                    
aggrgtDAPs= 1 
aggrgtdiff=0.03 
outputDAP=0      
dropini=5
droppro=.64            
drftthrsh=.4           
minSLdens=120         
minnsthrsh=.05       
nsthrsh=.2            
minSLthrsh=.2         
lwcthrsh_0 =0.01 
lwcthrsh_1 =0.03          
dysisomax=3
vw_thrsh = 5
vw_thrsh_days = 3

[AVAPRO-THOLDS-APS-SNP] 
damthrshnap=8
inithrshnap=999    
propthrshnap= 0.32
damthrshpap=18      
inithrshpap= 1.31       
propthrshpap=.42    
drftthrsh=3

[INFO]