[AVAPRO]
SIM_FOLDER_PATH     = ./output/example-folder/
OUTPUT_DIR          = NONE
OUTPUT_NAME         = NONE

rerun_find_WL          = 1
rerun_assign_avaprobs  = 1
run_visualize_avaprobs = 1

DATE_OPERA          = TODAY
initilization_type  = profile
drytime             = 6
wettime             = 15
debug               = 0
scmopt              = snp

# Only for type station
season_start        = 2023-01-01
season_end          = 2024-01-01

[AVAPRO-THOLDS-WL]
calcFEM=0          
owSCtaup=0                 
lookat= 0                    
aggrgtDAPs= 1 
aggrgtdiff=0.03 
outputDAP=0      
dropini=5
droppro=.64            
drftthrsh=.4           
minSLdens=120         
minnsthrsh=.05       
nsthrsh=.2            
minSLthrsh=.2         
lwcthrsh_0 =0.01 
lwcthrsh_1 =0.03          
dysisomax=3
vw_thrsh = 5
vw_thrsh_days = 3

[AVAPRO-THOLDS-APS-SNP] 
damthrshnap=99      
inithrshnap=999    
propthrshnap= 99     
damthrshpap=18      
inithrshpap= 1.31       
propthrshpap=.42    
drftthrsh=3

[INFO]
# Keep NONE for OUTPUT_DIR and OUTPUT_NAME if you have multiple sims and want plots in same folder as Pickle files
# Instead of having a simulation folder... Go for simulating lawis profiles numbers and numbers give pro and smet file, name via JSON file