################################################################################
# Copyright 2022 Avalanche Warning Service Tyrol                               #
################################################################################
# This is free software you can redistribute/modify under the terms of the     #
# GNU Lesser General Public License 3 or later: http://www.gnu.org/licenses    #
################################################################################

[Dtw_weights]
GTYPE                       = 0.75
HARDNESS                    = 0.25
DDATE                       = 0.0


[CONFIG-INFO]
# DDATE: 0.5 recommended, but currently no ddates available from .pro files!
# GTYPE: 0.375 recommended
# HARDNESS: 0.125 recommended
# New dimensions to Dtw-weights need to be included in aggregate_gridded_forecast.R!
