################################################################################
# Copyright 2024 Avalanche Warning Service Tyrol / Florian Herla               #
################################################################################
# This is free software you can redistribute/modify under the terms of the     #
# GNU Lesser General Public License 3 or later: http://www.gnu.org/licenses    #
################################################################################

[Aggregate]
DEBUG_MODE = TRUE
DAILY_TIME = 06:00

[Forecast]
SEASON_START = NA
SEASON_END = NA
DATE_OPERA = NA

[General]
NTASKS = 1

[DTW_weights]
GTYPE                       = 0.375
HARDNESS                    = 0.125
DDATE                       = 0.5

[Paths]
_aggregates_vstations_csv_file = _vstations_csv_file


[CONFIG-INFO]
# DTW_weights need to be adjusted if, for example, DDATE were not available from .pro files!
# DAILY_TIME is in time zone of profiles (as obtained by SMET file header)