################################################################################
# Configuration settings for snowpro.aggregatepro snow profile aggregation
# ------------------------------------------------------------------------------
# Find detailed documentation of all settings below.
################################################################################


[Aggregate]
daily_time                      = 06:00
plot_handhardness               = TRUE
plot_tsplain                    = TRUE
plot_tsstability                = TRUE
plot_leadtime_days_handhardness = 3
saveas_rds                      = TRUE
debug_mode                      = FALSE
progressbar                     = TRUE
initialize_from                 = date_opera

[General]
date_opera      = NA
season_start    = NA
season_end      = NA
nslopes         = 5
ncpus  = 1
ntasks = 1

[Advanced]
weights_gtype                   = 0.375
weights_hardness                = 0.125
weights_ddate                   = 0.5
sim_type                        = RTA_SCALING

[Paths]
_aggregates_vstations_csv_file  = _vstations_csv_file
_aggregates_snp_pro_dir         = _snp_output_dir
_aggregates_output_basedir      = _output_dir


# ---------------------------
# Documentation for Aggregate
# ---------------------------
# The 'Aggregate' section controls how snow profiles are processed and
# aggregated. Settings include time for daily processing and various plotting
# options.
#
# daily_time: Time of day for performing daily aggregations in HH:MM format. 
#             Higher-frequent aggregations not supported at this stage.
# plot_handhardness: Enable plotting of hand hardness graphs (TRUE or FALSE).
# plot_tsplain: Enable plotting of timeseries graphs with plain grain types (TRUE or FALSE).
# plot_tsstability: Enable plotting of timeseries graphs of grain type with shaded instability overplot (TRUE or FALSE).
# plot_leadtime_days_handhardness: Days ahead for plotting hand hardness.
# saveas_rds: Save results in RDS format (TRUE or FALSE).
# debug_mode: Enable debug mode for additional logging (TRUE or FALSE).
# progressbar: Display a progress bar in the console (TRUE or FALSE). Need R package `progress` installed to show.
# initialize_from: Starting date for aggregations (`date_opera`, `season_start`). 
#                  Output will be appended if `save_rds` is TRUE and the current aggregation resumes the file on disk.

# ----------------------------
# Documentation for Forecast
# ----------------------------
# The 'Forecast' section defines the operational period and aspects of the forecast.
# 
# date_opera: Operational date when aggregating on day-by-day basis. Otherwise it's best to set it equal to season_end.
# season_start: Start date of the snow profiles on disk (for the desired season).
# season_end: End date of the snow profiles on disk or the desired end date for aggregation (for the desired season).
# nslopes: Number of slope aspects to consider, 1 (flat field only) or 5 (flat field plus 4 cardinal aspects), SNOWPACK convention.

# -----------------------
# Documentation for General
# -----------------------
# General settings applicable across the module.
#
# ncpus: Number of CPU cores for parallel processing.
# ntasks: Number of tasks for distributing the workload.
# currently, if more cpus are available than tasks got distributed, there is no performance gain. An automated cpus_per_task
# computation will be implemented in the near future, so that each task can also be parallelized. At the moment, one task 
# corresponds to one row in the file `.input/aggregates_groupings/domain-summary.csv`.

# -----------------------
# Documentation for Advanced
# -----------------------
# Advanced settings for dynamic time warping and snow profile alignment.
#
# weights_gtype: Relative weight for grain type.
# weights_hardness: Relative weight for hardness.
# weights_ddate: Relative weight for deposition date. Make sure your .pro files contain that information!
# sim_type: Similarity measure for aligned snow profiles (RTA_SCALING, ...) found at R function sarp.snowprofile.alignment::simSP, 
#           e.g. here, https://www.rdocumentation.org/packages/sarp.snowprofile.alignment/versions/1.2.2/topics/simSP

# ---------------------
# Documentation for Paths
# ---------------------
# Paths for various input and output files and directories.
#
# _aggregates_vstations_csv_file: Path to vstations CSV file. `_vstations_csv_file` set in the context of AWSOME for automatic file detection.
# _aggregates_snp_pro_dir: Directory for .pro files. `_snp_output_dir` set in the context of AWSOME for automatic file detection.
# _aggregates_output_basedir: Directory to put resulting output folders, `aggregates-{domain}/` and `aggregates-figs-{domain}`. 
#                             `_output_dir` set in the context of AWSOME for automatic output handling.
